// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        CData/*0:0*/ top__DOT__cpu__DOT__is_ecall;
        VL_IN8(reset,0,0);
        VL_OUT8(is_halted,0,0);
        VL_OUT8(is_hit,0,0);
        VL_OUT8(is_miss,0,0);
        CData/*0:0*/ top__DOT__reset;
        CData/*0:0*/ top__DOT__clk;
        CData/*0:0*/ top__DOT__is_halted;
        CData/*0:0*/ top__DOT__is_hit;
        CData/*0:0*/ top__DOT__is_miss;
        CData/*0:0*/ top__DOT__cpu__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__is_halted;
        CData/*0:0*/ top__DOT__cpu__DOT__is_hit;
        CData/*0:0*/ top__DOT__cpu__DOT__is_miss;
        CData/*4:0*/ top__DOT__cpu__DOT__rs1;
        CData/*4:0*/ top__DOT__cpu__DOT__rs2;
        CData/*4:0*/ top__DOT__cpu__DOT__rd;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__alu_src;
        CData/*0:0*/ top__DOT__cpu__DOT__reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__pc_to_reg;
        CData/*4:0*/ top__DOT__cpu__DOT__alu_op;
        CData/*0:0*/ top__DOT__cpu__DOT__is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__branch;
        CData/*0:0*/ top__DOT__cpu__DOT__is_stall;
        CData/*4:0*/ top__DOT__cpu__DOT__func_code;
        CData/*0:0*/ top__DOT__cpu__DOT__alu_bcond;
        CData/*0:0*/ top__DOT__cpu__DOT__check_is_halted;
        CData/*1:0*/ top__DOT__cpu__DOT__ForwardA_sel;
        CData/*1:0*/ top__DOT__cpu__DOT__ForwardB_sel;
        CData/*1:0*/ top__DOT__cpu__DOT__mux_rs1_sel;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_rs2_sel;
        CData/*0:0*/ top__DOT__cpu__DOT__is_input_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_rw;
        CData/*0:0*/ top__DOT__cpu__DOT__is_ready;
        CData/*0:0*/ top__DOT__cpu__DOT__is_output_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_access;
        CData/*0:0*/ top__DOT__cpu__DOT__cache_stall;
        CData/*4:0*/ top__DOT__cpu__DOT__IF_ID_BHSR;
        CData/*0:0*/ top__DOT__cpu__DOT__IF_ID_is_flush;
        CData/*4:0*/ top__DOT__cpu__DOT__ID_EX_alu_op;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_alu_src;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_pc_to_reg;
        CData/*4:0*/ top__DOT__cpu__DOT__ID_EX_rd;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_is_halted;
        CData/*4:0*/ top__DOT__cpu__DOT__ID_EX_rs1;
        CData/*4:0*/ top__DOT__cpu__DOT__ID_EX_rs2;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_branch;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_is_jalr;
        CData/*4:0*/ top__DOT__cpu__DOT__ID_EX_BHSR;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_or_jmp;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_branch_taken;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_mem_read;
    };
    struct {
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_pc_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_reg_write;
        CData/*4:0*/ top__DOT__cpu__DOT__EX_MEM_rd;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_is_halted;
        CData/*0:0*/ top__DOT__cpu__DOT__MEM_WB_mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__MEM_WB_reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__MEM_WB_pc_to_reg;
        CData/*4:0*/ top__DOT__cpu__DOT__MEM_WB_rd;
        CData/*0:0*/ top__DOT__cpu__DOT__MEM_WB_is_halted;
        CData/*4:0*/ top__DOT__cpu__DOT__BHSR;
        CData/*0:0*/ top__DOT__cpu__DOT__is_correct;
        CData/*0:0*/ top__DOT__cpu__DOT__is_flush;
        CData/*0:0*/ top__DOT__cpu__DOT__pc__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__pc__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__pc__DOT__pc_write;
        CData/*0:0*/ top__DOT__cpu__DOT__pc__DOT__cache_stall;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__branch_or_jmp;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__ID_EX_is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__ID_EX_is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__ID_EX_branch;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__alu_bcond;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__ID_EX_branch_taken;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__ID_EX_BHSR;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__BHSR;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__IF_BHSR;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__IF_btb_index;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__ID_EX_btb_index;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__is_tag_match;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__try_to_branch;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__pred_taken;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__is_btb_output_valid;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__tag_table__DOT__IF_btb_index;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__tag_table__DOT__ID_EX_btb_index;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__tag_table__DOT__update_tag;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__tag_table__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__tag_table__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__predictor__DOT__actually_taken;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__predictor__DOT__IF_btb_index;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__predictor__DOT__ID_EX_btb_index;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__predictor__DOT__update_counter;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__predictor__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__predictor__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__predictor__DOT__pred_taken;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__btb__DOT__IF_btb_index;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__btb__DOT__ID_EX_btb_index;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__btb__DOT__update_table;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__btb__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__btb__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__bhsr__DOT__branch_or_jump;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__bhsr__DOT__update_bhsr;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__bhsr__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__PC_predict__DOT__bhsr__DOT__clk;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__bhsr__DOT__IF_BHSR;
        CData/*4:0*/ top__DOT__cpu__DOT__PC_predict__DOT__bhsr__DOT___branch_history;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_next_pc__DOT__sel;
        CData/*0:0*/ top__DOT__cpu__DOT__imem__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__imem__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__reg_file__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__reg_file__DOT__clk;
        CData/*4:0*/ top__DOT__cpu__DOT__reg_file__DOT__rs1;
        CData/*4:0*/ top__DOT__cpu__DOT__reg_file__DOT__rs2;
    };
    struct {
        CData/*4:0*/ top__DOT__cpu__DOT__reg_file__DOT__rd;
        CData/*0:0*/ top__DOT__cpu__DOT__reg_file__DOT__write_enable;
        CData/*6:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__part_of_inst;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__alu_src;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__write_enable;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__pc_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__branch;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__is_ecall;
        CData/*6:0*/ top__DOT__cpu__DOT__imm_gen__DOT__opcode;
        CData/*4:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__alu_op;
        CData/*6:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__funct7;
        CData/*2:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__funct3;
        CData/*6:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__opcode;
        CData/*4:0*/ top__DOT__cpu__DOT__alu__DOT__alu_op;
        CData/*0:0*/ top__DOT__cpu__DOT__alu__DOT__alu_bcond;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_rw_32_mux__DOT__sel;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_input_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__mem_rw;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_ready;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_output_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_hit;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_miss;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_data_mem_ready;
        CData/*3:0*/ top__DOT__cpu__DOT__cache__DOT__index_input;
        CData/*1:0*/ top__DOT__cpu__DOT__cache__DOT__offset_input;
        CData/*3:0*/ top__DOT__cpu__DOT__cache__DOT__clog2;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__valid_stored;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__dirty_stored;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_tag_match;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_cache_hit;
        CData/*1:0*/ top__DOT__cpu__DOT__cache__DOT__current_stage;
        CData/*1:0*/ top__DOT__cpu__DOT__cache__DOT__next_stage;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_write_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_write_dirty;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__tag_write_enable;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_write_enable;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT___is_output_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_memory_input_is_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_memory_output_is_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_memory_is_read;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_memory_is_write;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__ways;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_input_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_output_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_ready;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT___mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT___mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__request_arrived;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_mem_to_reg__DOT__sel;
        CData/*4:0*/ top__DOT__cpu__DOT__FU__DOT__ID_EX_rs1;
        CData/*4:0*/ top__DOT__cpu__DOT__FU__DOT__ID_EX_rs2;
        CData/*4:0*/ top__DOT__cpu__DOT__FU__DOT__EX_MEM_rd;
        CData/*4:0*/ top__DOT__cpu__DOT__FU__DOT__MEM_WB_rd;
    };
    struct {
        CData/*0:0*/ top__DOT__cpu__DOT__FU__DOT__EX_MEM_RegWrite;
        CData/*0:0*/ top__DOT__cpu__DOT__FU__DOT__MEM_WB_RegWrite;
        CData/*1:0*/ top__DOT__cpu__DOT__FU__DOT__ForwardA;
        CData/*1:0*/ top__DOT__cpu__DOT__FU__DOT__ForwardB;
        CData/*0:0*/ top__DOT__cpu__DOT__FU__DOT__rs1_mem_to_ex_forward;
        CData/*0:0*/ top__DOT__cpu__DOT__FU__DOT__rs1_wb_to_ex_forward;
        CData/*0:0*/ top__DOT__cpu__DOT__FU__DOT__rs2_mem_to_ex_forward;
        CData/*0:0*/ top__DOT__cpu__DOT__FU__DOT__rs2_wb_to_ex_forward;
        CData/*1:0*/ top__DOT__cpu__DOT__mux_forward_A__DOT__sel;
        CData/*1:0*/ top__DOT__cpu__DOT__mux_forward_B__DOT__sel;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_ID_EX_alu_src__DOT__sel;
        CData/*4:0*/ top__DOT__cpu__DOT__FEU__DOT__rs1;
        CData/*4:0*/ top__DOT__cpu__DOT__FEU__DOT__rs2;
        CData/*0:0*/ top__DOT__cpu__DOT__FEU__DOT__is_ecall;
        CData/*4:0*/ top__DOT__cpu__DOT__FEU__DOT__EX_MEM_rd;
        CData/*1:0*/ top__DOT__cpu__DOT__FEU__DOT__mux_rs1_sel;
        CData/*0:0*/ top__DOT__cpu__DOT__FEU__DOT__mux_rs2_sel;
        CData/*1:0*/ top__DOT__cpu__DOT__Mux_forwarding_rs1_dout__DOT__sel;
        CData/*0:0*/ top__DOT__cpu__DOT__Mux_forwarding_rs2_dout__DOT__sel;
        CData/*4:0*/ top__DOT__cpu__DOT__HDU__DOT__rs1;
        CData/*4:0*/ top__DOT__cpu__DOT__HDU__DOT__rs2;
        CData/*4:0*/ top__DOT__cpu__DOT__HDU__DOT__ID_EX_rd;
        CData/*4:0*/ top__DOT__cpu__DOT__HDU__DOT__EX_MEM_rd;
        CData/*0:0*/ top__DOT__cpu__DOT__HDU__DOT__ID_EX_mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__HDU__DOT__EX_MEM_mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__HDU__DOT__is_ecall;
        CData/*0:0*/ top__DOT__cpu__DOT__HDU__DOT__is_stall;
        CData/*0:0*/ top__DOT__cpu__DOT__HDU__DOT__is_load_hazard;
        CData/*0:0*/ top__DOT__cpu__DOT__HDU__DOT__is_ecall_hazard;
        CData/*0:0*/ __VdfgTmp_h69e9d136__0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*11:0*/ top__DOT__cpu__DOT__imm_gen__DOT__imm_I;
        SData/*11:0*/ top__DOT__cpu__DOT__imm_gen__DOT__imm_S;
        SData/*12:0*/ top__DOT__cpu__DOT__imm_gen__DOT__imm_B;
        IData/*31:0*/ top__DOT__cpu__DOT__current_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__next_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__imem_out;
        IData/*31:0*/ top__DOT__cpu__DOT__rs1_dout;
        IData/*31:0*/ top__DOT__cpu__DOT__rs2_dout;
        IData/*31:0*/ top__DOT__cpu__DOT__rd_din;
        IData/*31:0*/ top__DOT__cpu__DOT__pc_imm;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_rd_din;
        IData/*31:0*/ top__DOT__cpu__DOT__imm_gen_out;
        IData/*31:0*/ top__DOT__cpu__DOT__alu_in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__alu_in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__alu_result;
        IData/*31:0*/ top__DOT__cpu__DOT__dmem_out;
        IData/*31:0*/ top__DOT__cpu__DOT__forWard_B_out;
        IData/*31:0*/ top__DOT__cpu__DOT__forwarding_rs1_dout;
        IData/*31:0*/ top__DOT__cpu__DOT__forwarding_rs2_dout;
        IData/*31:0*/ top__DOT__cpu__DOT__in1_alu_out;
        IData/*31:0*/ top__DOT__cpu__DOT__in2_rd_din;
        IData/*31:0*/ top__DOT__cpu__DOT__mem_rw_32;
        IData/*31:0*/ top__DOT__cpu__DOT__IF_ID_inst;
        IData/*31:0*/ top__DOT__cpu__DOT__IF_ID_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_rs1_data;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_rs2_data;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_imm;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_ALU_ctrl_unit_input;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_pc;
    };
    struct {
        IData/*31:0*/ top__DOT__cpu__DOT__EX_MEM_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__EX_MEM_alu_out;
        IData/*31:0*/ top__DOT__cpu__DOT__EX_MEM_dmem_data;
        IData/*31:0*/ top__DOT__cpu__DOT__MEM_WB_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_1;
        IData/*31:0*/ top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_2;
        IData/*31:0*/ top__DOT__cpu__DOT__predicted_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__correct_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__pc__DOT__next_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__pc__DOT__current_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT__IF_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT__ID_EX_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT__pc_imm;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT__alu_result;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT__predicted_pc;
        IData/*24:0*/ top__DOT__cpu__DOT__PC_predict__DOT__IF_tag;
        IData/*24:0*/ top__DOT__cpu__DOT__PC_predict__DOT__ID_EX_tag;
        IData/*24:0*/ top__DOT__cpu__DOT__PC_predict__DOT__tag_from_table;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT__target_out;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT____Vcellinp__btb__ID_EX_pc;
        IData/*24:0*/ top__DOT__cpu__DOT__PC_predict__DOT__tag_table__DOT__ID_EX_tag;
        IData/*24:0*/ top__DOT__cpu__DOT__PC_predict__DOT__tag_table__DOT__corresponding_tag;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT__tag_table__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT__predictor__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT__btb__DOT__ID_EX_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT__btb__DOT__target_out;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT__btb__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__PC_predict__DOT__bhsr__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_next_pc__DOT__in0;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_next_pc__DOT__in1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_next_pc__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__addr;
        IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__dout;
        IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__imem_addr;
        IData/*31:0*/ top__DOT__cpu__DOT__reg_file__DOT__rd_din;
        IData/*31:0*/ top__DOT__cpu__DOT__reg_file__DOT__rs1_dout;
        IData/*31:0*/ top__DOT__cpu__DOT__reg_file__DOT__rs2_dout;
        IData/*31:0*/ top__DOT__cpu__DOT__reg_file__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__imm_gen__DOT__part_of_inst;
        IData/*31:0*/ top__DOT__cpu__DOT__imm_gen__DOT__imm_gen_out;
        IData/*19:0*/ top__DOT__cpu__DOT__imm_gen__DOT__imm_J;
        IData/*16:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__part_of_inst;
        IData/*31:0*/ top__DOT__cpu__DOT__alu__DOT__alu_in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__alu__DOT__alu_in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__alu__DOT__alu_result;
        IData/*31:0*/ top__DOT__cpu__DOT__adder_pc_imm__DOT__in1;
        IData/*31:0*/ top__DOT__cpu__DOT__adder_pc_imm__DOT__in2;
        IData/*31:0*/ top__DOT__cpu__DOT__adder_pc_imm__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__mem_rw_32_mux__DOT__in0;
        IData/*31:0*/ top__DOT__cpu__DOT__mem_rw_32_mux__DOT__in1;
        IData/*31:0*/ top__DOT__cpu__DOT__mem_rw_32_mux__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__addr;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__din;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__dout;
        IData/*23:0*/ top__DOT__cpu__DOT__cache__DOT__tag_input;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_stored;
        IData/*23:0*/ top__DOT__cpu__DOT__cache__DOT__tag_stored;
        IData/*23:0*/ top__DOT__cpu__DOT__cache__DOT__tag_write_tobe_cache;
        IData/*23:0*/ top__DOT__cpu__DOT__cache__DOT__tag_read_from_cache;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_write_tobe_cache;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_read_from_cache;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_memory_address;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_memory_data_input;
    };
    struct {
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_memory_data_output;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__addr;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__din;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__dout;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__delay_counter;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT___mem_addr;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT___din;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_mem_to_reg__DOT__in0;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_mem_to_reg__DOT__in1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_mem_to_reg__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forward_A__DOT__in0;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forward_A__DOT__in1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forward_A__DOT__in2;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forward_A__DOT__in3;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forward_A__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forward_B__DOT__in0;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forward_B__DOT__in1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forward_B__DOT__in2;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forward_B__DOT__in3;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forward_B__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ID_EX_alu_src__DOT__in0;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ID_EX_alu_src__DOT__in1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ID_EX_alu_src__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__Mux_forwarding_rs1_dout__DOT__in0;
        IData/*31:0*/ top__DOT__cpu__DOT__Mux_forwarding_rs1_dout__DOT__in1;
        IData/*31:0*/ top__DOT__cpu__DOT__Mux_forwarding_rs1_dout__DOT__in2;
        IData/*31:0*/ top__DOT__cpu__DOT__Mux_forwarding_rs1_dout__DOT__in3;
        IData/*31:0*/ top__DOT__cpu__DOT__Mux_forwarding_rs1_dout__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__Mux_forwarding_rs2_dout__DOT__in0;
        IData/*31:0*/ top__DOT__cpu__DOT__Mux_forwarding_rs2_dout__DOT__in1;
        IData/*31:0*/ top__DOT__cpu__DOT__Mux_forwarding_rs2_dout__DOT__out;
        IData/*31:0*/ __VactIterCount;
        VL_OUT(print_reg[32],31,0);
        VlUnpacked<IData/*31:0*/, 32> top__DOT__print_reg;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu__DOT__print_reg;
        VlUnpacked<IData/*24:0*/, 32> top__DOT__cpu__DOT__PC_predict__DOT__tag_table__DOT___tag_table;
        VlUnpacked<CData/*1:0*/, 32> top__DOT__cpu__DOT__PC_predict__DOT__predictor__DOT__counter;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu__DOT__PC_predict__DOT__btb__DOT__target_table;
        VlUnpacked<IData/*31:0*/, 16384> top__DOT__cpu__DOT__imem__DOT__mem;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu__DOT__reg_file__DOT__print_reg;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu__DOT__reg_file__DOT__rf;
        VlUnpacked<VlWide<4>/*127:0*/, 16> top__DOT__cpu__DOT__cache__DOT__data_storage;
        VlUnpacked<IData/*23:0*/, 16> top__DOT__cpu__DOT__cache__DOT__tag_storage;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__cpu__DOT__cache__DOT__valid_storage;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__cpu__DOT__cache__DOT__dirty_storage;
        VlUnpacked<VlWide<4>/*127:0*/, 16384> top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__MEM_DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__LINE_SIZE = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__NUM_SETS = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__NUM_WAYS = 1U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__MEM_DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__DELAY = 0x00000032U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__BLOCK_SIZE = 0x00000010U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
